export default{
    path: '/shouye',
    component:()=>import('@/views/shouye/shouye'),
   	children:[
   	    {
   	        path:'zmian',
			name:'shouye',
   	        component:()=>import('@/components/zmian/zmian.vue'),
   	    },
   		{
   		    path:'rshi',
   		    component:()=>import('@/components/rshi/rshi.vue'),
   		},
		{
		    path:'guanli',
		    component:()=>import('@/components/guanli/guanli.vue'),
		},
		{
		    path:'peizhi',
		    component:()=>import('@/components/peizhi/peizhi.vue'),
			children:[
			    {
			        path:'zhaop',
			        component:()=>import('@/components/zhaop/zhaop.vue'),
			    },
				{
				    path:'shiyong',
				    component:()=>import('@/components/shiyong/shiyong.vue'),
				},
				{
				    path:'linshi',
				    component:()=>import('@/components/linshi/linshi.vue'),
				},
				{
				    path:'tuixiu',
				    component:()=>import('@/components/tuixiu/tuixiu.vue'),
				},
				{
				    path:'lizhi',
				    component:()=>import('@/components/lizhi/lizhi.vue'),
				},
			    {
			        path:'/shouye/peizhi',
			        redirect:'/shouye/peizhi/zhaop'
			     }
			]
		},
		{
		    path:'kaoq',
		    component:()=>import('@/components/kaoq/kaoq.vue'),
			children:[
			    {
			        path:'chuc',
			        component:()=>import('@/components/kaoqing/chuc.vue'),
			    },
				{
				    path:'jiaban',
				    component:()=>import('@/components/kaoqing/jiaban.vue'),
				},
				{
				    path:'qingxiu',
				    component:()=>import('@/components/kaoqing/qingxiu.vue'),
				},
				{
				    path:'tiaoxiu',
				    component:()=>import('@/components/kaoqing/tiaoxiu.vue'),
				},
				{
				    path:'waichu',
				    component:()=>import('@/components/kaoqing/waichu.vue'),
				},
				{
				    path:'waiqing',
				    component:()=>import('@/components/kaoqing/waiqing.vue'),
				},
			    {
			        path:'/shouye/kaoq',
			        redirect:'/shouye/kaoq/chuc'
			     }
			]
		},
		{
		    path:'guanh',
		    component:()=>import('@/components/guanh/guanh.vue'),
			children:[
			    {
			        path:'laodong',
			        component:()=>import('@/components/fuli/laodong.vue'),
					children:[
						{
						path:'xiangq',
						component:()=>import('@/components/xiangq/xiangq.vue'),
						}
					]
			    },
				{
				    path:'shengr',
				    component:()=>import('@/components/fuli/shengr.vue'),
				},
				{
				    path:'yuangong',
				    component:()=>import('@/components/fuli/yuangong.vue'),
				},
				{
				    path:'zhuanx',
				    component:()=>import('@/components/fuli/zhuanx.vue'),
				},
			    {
			        path:'/shouye/guanh',
			        redirect:'/shouye/guanh/laodong'
			     }
			]
		},
		{
		    path:'jixiao',
		    component:()=>import('@/components/jixiao/jixiao.vue'),
			children:[
			    {
			        path:'yuedi',
			        component:()=>import('@/components/jixiaog/yuedi.vue'),
			    },
				{
				    path:'jidu',
				    component:()=>import('@/components/jixiaog/jidu.vue'),
				},
				{
				    path:'niandu',
				    component:()=>import('@/components/jixiaog/niandu.vue'),
				},
				{
				    path:'yuangong',
				    component:()=>import('@/components/fuli/yuangong.vue'),
				},
				{
				    path:'xinzeng',
				    component:()=>import('@/components/jixiaog/xinzeng.vue'),
				},
			    {
			        path:'/shouye/jixiao',
			        redirect:'/shouye/jixiao/yuedi'
			     }
			]
		},
		{
		    path:'tuichu',
		    component:()=>import('@/components/tuichu/tuichu.vue'),
		},
   	    {
   	        path:'/shouye',
   	        redirect:'/shouye/zmian'
   	     }
   	]
}